[TASK-21] Mini map
TaskStudio/Projet_Annuel_3RVJV pull request #27
Opened 2024-06-10 10:33 UTC by Onsraa

# Description
Ajout de minimap

# Changements importants
- Ajout d'un dossier UI à la racine du dossier Assets
- Réorganisation des fichiers

2024-06-10 10:35 UTC, Onsraa commented
Vérifiez si vos fichiers ne sont pas cassés. J'ai réorganisé les fichiers pour plus de lisibilité.

2024-06-11 09:03 UTC, Anakaryna requested changes
Il s'ont passés où nos scenes et entités ? Et les scripts associés ? 
😢

2024-06-11 09:37 UTC, Anakaryna requested changes
La scene freeze apres destruction d'une base mais ne load pas le pannel de endgame pour recommencer ou quitter la partie 

![image](https://github.com/TaskStudio/projet-annuel/assets/78374876/ff8b648c-ecd4-41bf-b320-b4f2e8a70f55)

2024-06-11 10:35 UTC, MrSebi06 commented
De mon côté le rectangle de sélection disparait pas lorsqu'on relâche le clic, je suis obligé de recliquer

2024-06-11 16:32 UTC, merged